# Generated by Django 5.0.8 on 2024-08-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "pic_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("sex", models.CharField(blank=True, max_length=10, null=True)),
                ("private_mode", models.BooleanField(default=False)),
                (
                    "account_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "custom_email",
                    models.EmailField(blank=True, max_length=100, null=True),
                ),
                ("active_until_date", models.DateField(blank=True, null=True)),
                (
                    "sms_left",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "extra_sms",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "users",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "indexes": [
                    models.Index(fields=["is_active"], name="users_is_acti_847b48_idx"),
                    models.Index(
                        fields=["custom_email"], name="users_custom__1433bf_idx"
                    ),
                ],
            },
        ),
    ]
