# Generated by Django 5.0.8 on 2024-08-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bot_name",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "email_address",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "last_read_message_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "bot_account",
                "verbose_name_plural": "bot_accounts",
                "db_table": "bot_accounts",
                "indexes": [
                    models.Index(
                        fields=["bot_name", "is_active"],
                        name="bot_account_bot_nam_221047_idx",
                    ),
                    models.Index(
                        fields=["email_address"], name="bot_account_email_a_0b0a40_idx"
                    ),
                    models.Index(
                        fields=["last_read_message_id"],
                        name="bot_account_last_re_9089f6_idx",
                    ),
                ],
            },
        ),
    ]
