# Generated by Django 5.0.8 on 2024-08-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_botaccount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="botaccount", old_name="password", new_name="corrlinks_password",
        ),
        migrations.AddField(
            model_name="botaccount",
            name="email_password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
