# Generated by Django 5.0.8 on 2024-08-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_password_botaccount_corrlinks_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="botaccount",
            name="email_url",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
