# Generated by Django 5.0.8 on 2024-09-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_botaccount_email_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="botaccount",
            options={
                "verbose_name": "Bot account",
                "verbose_name_plural": "Bot accounts",
            },
        ),
    ]
