# Generated by Django 5.0.8 on 2024-08-20 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("process_emails", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "contacts",
                "verbose_name_plural": "contacts",
                "db_table": "contacts",
            },
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "DEBUG"),
                            ("INFO", "INFO"),
                            ("WARNING", "WARNING"),
                            ("ERROR", "ERROR"),
                            ("CRITICAL", "CRITICAL"),
                        ],
                        max_length=10,
                    ),
                ),
                ("module", models.CharField(blank=True, max_length=255, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("message_id", models.CharField(blank=True, max_length=255, null=True)),
                ("exception_details", models.TextField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=50, null=True)),
                ("additional_data", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "logs",
                "verbose_name_plural": "logs",
                "db_table": "logs",
            },
        ),
        migrations.CreateModel(
            name="SMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("text_id", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "direction",
                    models.CharField(
                        choices=[("Inbound", "Inbound"), ("Outbound", "Outbound")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Sent", "Sent"),
                            ("Delivered", "Delivered"),
                            ("Failed", "Failed"),
                            ("Unknown", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_processed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.contact"
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process_emails.email",
                    ),
                ),
            ],
            options={
                "verbose_name": "sms",
                "verbose_name_plural": "sms",
                "db_table": "sms",
            },
        ),
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("Credit", "Credit"), ("Debit", "Debit")],
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "balance_after",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction_history",
                "verbose_name_plural": "transaction_history",
                "db_table": "transaction_history",
            },
        ),
        migrations.CreateModel(
            name="UserMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_content", models.TextField()),
                ("message_type", models.CharField(max_length=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user_messages",
                "verbose_name_plural": "user_messages",
                "db_table": "user_messages",
            },
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["user"], name="contacts_user_id_502575_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["phone_number"], name="contacts_phone_n_69cfc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(fields=["user"], name="logs_user_id_1f4728_idx"),
        ),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(fields=["log_level"], name="logs_log_lev_268790_idx"),
        ),
        migrations.AddIndex(
            model_name="sms",
            index=models.Index(fields=["contact"], name="sms_contact_6fc07b_idx"),
        ),
        migrations.AddIndex(
            model_name="sms",
            index=models.Index(fields=["email"], name="sms_email_i_f3730b_idx"),
        ),
        migrations.AddIndex(
            model_name="sms",
            index=models.Index(fields=["text_id"], name="sms_text_id_4a6c43_idx"),
        ),
        migrations.AddIndex(
            model_name="sms",
            index=models.Index(fields=["is_processed"], name="sms_is_proc_bcbd69_idx"),
        ),
        migrations.AddIndex(
            model_name="transactionhistory",
            index=models.Index(
                fields=["user", "created_at"], name="transaction_user_id_fb6fd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionhistory",
            index=models.Index(
                fields=["reference_id"], name="transaction_referen_b07c68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionhistory",
            index=models.Index(fields=["status"], name="transaction_status_e34d22_idx"),
        ),
        migrations.AddIndex(
            model_name="usermessage",
            index=models.Index(fields=["user"], name="user_messag_user_id_e33a49_idx"),
        ),
    ]
