# Generated by Django 5.0.8 on 2024-09-10 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_processeddata"),
        ("process_emails", "0002_email_bot_alter_email_message_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactManagementResponseMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=255)),
                ("response_content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="process_emails.email",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "contact_management_response_message",
                "verbose_name_plural": "contact_management_response_messages",
                "db_table": "contact_management_response_messages",
                "indexes": [
                    models.Index(
                        fields=["user"], name="contact_man_user_id_0498c9_idx"
                    ),
                    models.Index(
                        fields=["email"], name="contact_man_email_i_31eaae_idx"
                    ),
                    models.Index(
                        fields=["status"], name="contact_man_status_60182c_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="contact_man_created_92eb06_idx"
                    ),
                    models.Index(
                        fields=["message_id"], name="contact_man_message_43cdde_idx"
                    ),
                ],
            },
        ),
    ]
