# Generated by Django 5.0.8 on 2024-09-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_contactmanagementresponsemessages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmanagementresponsemessages",
            options={
                "verbose_name": "Contact management response message",
                "verbose_name_plural": "Contact management response messages",
            },
        ),
    ]
