# Generated by Django 5.0.8 on 2024-09-10 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_botaccount_options"),
        ("core", "0004_alter_contactmanagementresponsemessages_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmanagementresponsemessages",
            name="bot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.botaccount",
            ),
        ),
    ]
