# Generated by Django 5.0.8 on 2024-09-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_contactmanagementresponsemessages_bot"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="contactmanagementresponsemessages",
            name="contact_man_user_id_0498c9_idx",
        ),
        migrations.RemoveIndex(
            model_name="contactmanagementresponsemessages",
            name="contact_man_email_i_31eaae_idx",
        ),
        migrations.RemoveIndex(
            model_name="contactmanagementresponsemessages",
            name="contact_man_status_60182c_idx",
        ),
        migrations.RemoveIndex(
            model_name="contactmanagementresponsemessages",
            name="contact_man_created_92eb06_idx",
        ),
        migrations.RemoveIndex(
            model_name="contactmanagementresponsemessages",
            name="contact_man_message_43cdde_idx",
        ),
        migrations.RemoveField(
            model_name="contactmanagementresponsemessages", name="bot",
        ),
        migrations.RemoveField(
            model_name="contactmanagementresponsemessages", name="email",
        ),
        migrations.RemoveField(
            model_name="contactmanagementresponsemessages", name="message_id",
        ),
        migrations.RemoveField(
            model_name="contactmanagementresponsemessages", name="status",
        ),
        migrations.RemoveField(
            model_name="contactmanagementresponsemessages", name="user",
        ),
        migrations.AddField(
            model_name="contactmanagementresponsemessages",
            name="message_key",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
