# Generated by Django 5.0.8 on 2024-09-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0006_remove_contactmanagementresponsemessages_contact_man_user_id_0498c9_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contactmanagementresponsemessages",
            index=models.Index(
                fields=["message_key"], name="contact_man_message_ff313f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactmanagementresponsemessages",
            index=models.Index(
                fields=["created_at"], name="contact_man_created_92eb06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactmanagementresponsemessages",
            index=models.Index(
                fields=["updated_at"], name="contact_man_updated_d884e5_idx"
            ),
        ),
    ]
