# Generated by Django 5.0.8 on 2024-09-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0007_contactmanagementresponsemessages_contact_man_message_ff313f_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactManagementResponseMessages", new_name="ResponseMessages",
        ),
    ]
