# Generated by Django 5.0.8 on 2024-09-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_contactmanagementresponsemessages_responsemessages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="responsemessages",
            options={
                "verbose_name": "Response message",
                "verbose_name_plural": "Response messages",
            },
        ),
        migrations.RenameIndex(
            model_name="responsemessages",
            new_name="response_me_message_b8204f_idx",
            old_name="contact_man_message_ff313f_idx",
        ),
        migrations.RenameIndex(
            model_name="responsemessages",
            new_name="response_me_created_c08fb2_idx",
            old_name="contact_man_created_92eb06_idx",
        ),
        migrations.RenameIndex(
            model_name="responsemessages",
            new_name="response_me_updated_356cd4_idx",
            old_name="contact_man_updated_d884e5_idx",
        ),
        migrations.AlterModelTable(name="responsemessages", table="response_messages",),
    ]
