OPERATIONAL_DESCRIPTION = (
        "Handles incoming SMS webhook requests from the SMS service provider. "
        "This endpoint processes incoming SMS messages, verifies the authenticity of the request, "
        "and logs the message details into the database. The webhook is protected by an optional token "
        "system which, if enabled (i.e., TEST_MODE is False), validates the request to prevent unauthorized access. "
        "\n\n"
        "### Request Parameters:"
        "\n- `textId` (string, required): The unique identifier assigned to the SMS by the SMS service provider."
        "\n- `fromNumber` (string, required): The phone number from which the SMS was sent. It should be in international format."
        "\n- `text` (string, required): The content of the SMS message received."
        "\n- `data` (string, optional, required if TEST_MODE is False): An authentication token used to validate the webhook request. This token must be included if TEST_MODE is set to False, ensuring that the request is genuine and authorized."
        "\n\n"
        "### Response:"
        "\n- `200 OK`: The request was successfully processed. The response contains information about the email and contact associated with the SMS if found."
        "\n  - `email` (string, optional): The email address associated with the SMS if available. Otherwise, null."
        "\n  - `contact` (string, optional): The contact name associated with the SMS if available. Otherwise, null."
        "\n\n"
        "### Error Responses:"
        "\n- `403 Forbidden`: The request was rejected due to an invalid or expired token. This error is returned if the `data` field is missing or the token is invalid when TEST_MODE is False."
        "\n  - `error` (string): A message indicating that the token is invalid or expired."
        "\n- `400 Bad Request`: An error occurred while processing the SMS data. This might be due to issues such as missing parameters or database errors."
        "\n  - `error` (string): A detailed error message describing what went wrong during processing."
        "\n\n"
        "### Example Request:"
        "\n```json"
        "\n{"
        "\n  \"textId\": \"abc123\","
        "\n  \"fromNumber\": \"+1234567890\","
        "\n  \"text\": \"Hello World!\","
        "\n  \"data\": \"your_auth_token_here\""
        "\n}"
        "\n```"
        "\n\n"
        "### Example Response:"
        "\n```json"
        "\n{"
        "\n  \"email\": \"example@example.com\","
        "\n  \"contact\": \"John Doe\""
        "\n}"
        "\n```"
    )
