# Generated by Django 5.0.8 on 2024-08-23 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("process_emails", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("text_id", models.CharField(blank=True, max_length=255, null=True)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "direction",
                    models.CharField(
                        choices=[("Inbound", "Inbound"), ("Outbound", "Outbound")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Sent", "Sent"),
                            ("Delivered", "Delivered"),
                            ("Failed", "Failed"),
                            ("Unknown", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_processed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.contact"
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process_emails.email",
                    ),
                ),
            ],
            options={
                "verbose_name": "sms",
                "verbose_name_plural": "sms",
                "db_table": "sms",
                "indexes": [
                    models.Index(fields=["contact"], name="sms_contact_6fc07b_idx"),
                    models.Index(fields=["email"], name="sms_email_i_f3730b_idx"),
                    models.Index(fields=["text_id"], name="sms_text_id_4a6c43_idx"),
                    models.Index(
                        fields=["is_processed"], name="sms_is_proc_bcbd69_idx"
                    ),
                ],
            },
        ),
    ]
