# Generated by Django 5.0.8 on 2024-08-23 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=100, unique=True)),
                ("sent_date_time", models.DateTimeField()),
                ("subject", models.CharField(max_length=100)),
                ("body", models.TextField()),
                ("is_processed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "emails",
                "verbose_name_plural": "emails",
                "db_table": "emails",
                "indexes": [
                    models.Index(
                        fields=["user", "sent_date_time"],
                        name="emails_user_id_f0098f_idx",
                    ),
                    models.Index(
                        fields=["is_processed"], name="emails_is_proc_301c04_idx"
                    ),
                ],
            },
        ),
    ]
