# Generated by Django 5.0.8 on 2024-08-28 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_botaccount"),
        ("process_emails", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="bot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.botaccount",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="message_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="email",
            index=models.Index(fields=["bot"], name="emails_bot_id_3ed334_idx"),
        ),
    ]
