version: '3.8'

services:
  splash:
    image: scrapinghub/splash:latest
    ports:
      - "8050:8050"
    networks:
      - internal_network
    deploy:
      mode: replicated
      replicas: 5
      restart_policy:
        condition: on-failure

networks:
  internal_network:
    external: true
